votingsys/votingsys/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('votingsysApp.urls')),
    path('admin/', admin.site.urls),
]

votingsys/votingsysApp/urls.py
from unicodedata import name
from django.urls import path
from django.conf import settings
from . import views

app_name = 'votingsysApp'

urlpatterns =[ 
    path('', views.index, name='index'),
    path('newreg1/', views.newreg1, name='newreg1'),
    path('new/', views.new, name='new'),
    path('homepage/', views.homepage, name='homepage'),
    path('application/', views.application, name='application'),
    path('result/', views.result, name='result'),
    path('comelec/', views.comelec, name='comelec'),
    path('peoples/', views.peoples, name='peoples'),
    path('delete/<int:id>', views.delete, name='delete'),
    path('userlogin/', views.userlogin, name='userlogin'),
    path('comeleclog/', views.comeleclog, name='comeleclog'),
    path('regcomelec/', views.regcomelec, name='regcomelec'),
    path('regcom/', views.regcom, name='regcom'),
    path('comlog/', views.comlog, name='comlog'),
]

votingsys/votingsysApp/models.py
from django.db import models
import datetime
import os

# Create your models here.
def filename(request, filename):
    old_filename = filename
    timenow = datetime.datetime.now().strftime('%Y%m%d%H%M%S')
    filename = "%s%s", (timenow, old_filename)
    return os.path.join('uploads/', filename)

class newreg(models.Model):
    name = models.CharField(max_length=15, null=False)
    idno = models.CharField(max_length=15, null=False)
    email = models.EmailField(max_length=50, null=False)
    password = models.CharField(max_length=15,null=False)
    
class comelecreg(models.Model):
    name = models.CharField(max_length=15, null=False)
    idno = models.CharField(max_length=15, null=False)
    email = models.EmailField(max_length=50, null=False)
    password = models.CharField(max_length=15,null=False)

class candidates(models.Model):
    gender = [
        ('FEMALE', 'FEMALE'),
        ('MALE', 'MALE'),
    ]

    firstname = models.CharField(max_length=15, null=False)
    surname = models.CharField(max_length=15,null=False)
    course = models.CharField(max_length=15, null=False)
    age = models.IntegerField(null=False)
    gender = models.CharField(max_length=7, choices=gender,null=False)
    position = models.CharField(max_length=15, null=False)
    partylist = models.CharField(max_length=15,null=False)
    image = models.ImageField(upload_to='filepath', null=False)
    description = models.CharField(max_length=600, null=False)

votingsys/votingsysApp/forms.py
from django import forms
from .models import newreg

class newregForm(forms.ModelForm):
    class Meta:
        model= newreg
        fields= ["firstname","idno", "email", "password", "confirm_passsword"]	

votingsys/votingsysApp/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.models import User, auth
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from .models import newreg
from .models import candidates
from .models import comelecreg
import mysql.connector as sql

installed_apps = ['votingsysApp']

# Create your views here.
def index(request):#login student
    return render(request, 'votingsysApp/index.html')

def newreg1(request):# signup student
    return render(request, 'votingsysApp/newreg.html')

# student registration
def new(request):
    if request.method=='POST':
        name = request.POST.get('name')
        email = request.POST.get('email')
        idno = request.POST.get('idno')
        password = request.POST.get('password')
        # confirm_password = request.POST.get('confirm_password'),
        data = newreg.objects.create(name=name, email=email, idno=idno, password=password)
        data.save()
        return render(request, 'votingsysApp/index.html')



def comeleclog(request):# comelec login
    return render(request, 'votingsysApp/comelec_login.html')

def regcomelec(request):# comelec signup
    return render(request, 'votingsysApp/comelec_reg.html')


# -------comelec registration
def regcom(request):
    if request.method=='POST':
        name = request.POST.get('name')
        email = request.POST.get('email')
        idno = request.POST.get('idno')
        pas = request.POST.get('pas')
        # cpassword = request.POST.get('cpassword'),
        data = comelecreg.objects.create(name=name, email=email, idno=idno, password=pas)
        data.save()
        return render(request, 'votingsysApp/comelec_login.html')


# ------comelec log in
def comlog(request):
    if request.method=="POST":
        n=sql.connect(host="localhost",user="root",password="",database='vsdb')
        cursor=n.cursor()
        e=request.POST
        for key,value in e.items():
            if key=="email":
                email=value
            if key=="pass":
                password=value
        
        l="select * from votingsysapp_comelecreg where email='{}' and password='{}'".format(email,password)
        
        cursor.execute(l)
        h=tuple(cursor.fetchall())
        if h==():
            return render(request, 'votingsysApp/comelec_login.html')
            
        else:
            data = comelecreg.objects.filter(email=email)
          
            return redirect('/comelec', {'data':data})

    return render(request, 'votingsysApp/comeleclog.html')


#     user login


# def login(request):
#     if request.method=='POST':
#         username = request.POST.get('email')
#         password = request.POST.get('pass')
#         user = authenticate(username=username, password=password)
    


def userlogin(request):
    if request.method=="POST":
        m=sql.connect(host="localhost",user="root",password="",database='vsdb')
        cursor=m.cursor()
        d=request.POST
        for key,value in d.items():
            if key=="email":
                email=value
            if key=="pass":
                password=value
        
        c="select * from votingsysapp_newreg where email='{}' and password='{}'".format(email,password)
        
        cursor.execute(c)
        t=tuple(cursor.fetchall())
        if t==():
            return render(request, 'votingsysApp/index.html')
            
        else:
            data = newreg.objects.filter(email=email)
          
            return render(request, 'votingsysApp/homepage.html', {'data':data})

    return render(request, 'votingsysApp/index.html')
         

#                  candidates


def peoples(request):
    if request.method=='POST':
        firstname = request.POST.get('firstname')
        surname = request.POST.get('surname')
        course = request.POST.get('course')
        age = request.POST.get('age')
        gender=request.POST.get('gender')
        position=request.POST.get('position')
        partylist=request.POST.get('partylist')
        image=request.POST.get('image')
        lala=request.POST.get('lala')
        
        datas = candidates.objects.create(firstname=firstname, surname=surname, course=course, age=age, gender=gender, position=position, partylist=partylist, image=image, description=lala)
        datas.save()
    
        return redirect('/homepage')
    
    
def delete(request, id):
    data = candidates.objects.get(id=id)
    data.delete()
    return redirect('/comelec')

def homepage(request):
    data = newreg.objects.all()
    return render(request, 'votingsysApp/homepage.html', {'data':data})

def result(request):
    return render(request, 'votingsysApp/result.html')

def comelec(request):
    nef1 = candidates.objects.all()
    return render(request, 'votingsysApp/comelec.html', {'nef1':nef1})

def application(request):
    return render(request, 'votingsysApp/application.html')

votingsys/votingsysApp/templates/votingsysApp/application.html
<!DOCTYPE html> {% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> CANDIDACY</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
    <link rel="stylesheet" href="{%static 'css/application.css' %}">
</head>

<body>
    <div class="sheet">
        <div class="a">
            <img src="{%static 'images/usg.png' %}" width="150px" height="150px">
        </div>
        <div class="b">
            <p> APPLICATION FOR CANDIDACY </p>
        </div>
    </div>
    <div class="mid">
        <form action="/peoples/" method="post">
            {% csrf_token %}
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="firstname">FIRSTNAME</label>
                    <input type="text" class="form-control" id="firstname" name="firstname" required>
                </div>
                <div class="form-group col-md-6">
                    <label for="surname">SURNAME</label>
                    <input type="text" class="form-control" id="surname" name="surname" required>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-5">
                    <label for="cs">COURSE & SECTION</label>
                    <input type="text" class="form-control" id="cs" name="course" required>
                </div>

                <div class="form-group col-md-3">
                    <label for="age">AGE</label>
                    <input type="text" class="form-control" id="age" name="age">
                </div>
                <div class="form-group col-md-1 ">
                    <label for="gender">GENDER</label>
                    <select id="inputState" class="gender" name="gender" required>
                        <option selected disabled value="">Choose...</option>
                        <option value="Female">Female</option>
                        <option value="Male">Male</option>
                    </select>
                </div>
                <div class="form-group col-md-3">
                    <label for="pos">POSITION</label>
                    <input type="text" class="form-control" id="pos" name="position">
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="party">PARTYLIST</label>
                    <input type="text" class="form-control" id="party" name="partylist">
                </div>
                <div class="form-group col-md-2">
                    <label for="img">UPLOAD YOUR PHOTO:</label>
                    <input type="file" name="image" id="img">
                </div>
            </div>
            <div class="formss">
                <div class="formss">
                    <label for="desc">DESCRIBE YOURSELF:</label>
                    <input type="text" name="lala" id="desc">
                </div>

            </div>
            <div class="bttn">
                <a href="{% url 'votingsysApp:homepage' %}" id="cancel">CANCEL</a>
                <input class="aaa" id="pindot" type="submit" name="submit" value="SUBMIT">
            </div>
        </form>

        <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js" integrity="sha384-VHvPCCyXqtD5DqJeNxl2dtTyhF78xXNXdkwX1CZeRusQfRKp+tA7hAShOK/B/fQ2" crossorigin="anonymous"></script>

</body>

</html>

votingsys/votingsysApp/templates/votingsysApp/comelec.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>COMELEC</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
    <link rel="stylesheet" href="{%static 'css/comelec.css' %}">

</head>

<body>
    <div class="sheet">
        <div class="top">
            <div class="img">
                <img src="{%static 'images/usg.png' %}" width="200px" height="200px">
            </div>
            <div class="sulat">
                <div class="in">
                    <p> COMELEC OFFICIAL </p>
                    <p>CANDIDATE LIST</p>
                </div>
            </div>

        </div>
    </div>
    <form method='GET'>
        <div class="mid">
            <div class="table">
                <table id="candidates" class="table d-print-table-cell">
                    <thead>
                        <tr>
                            <th scope="col">Firstname</th>
                            <th scope="col">Surname</th>
                            <th scope="col">Age</th>
                            <th scope="col">Course & Section</th>
                            <th scope="col">Position</th>
                            <th scope="col">Partylist</th>
                            <th scope="col">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for files in nef1 %}
                        <tr>
                            <td>{{files.firstname}}</td>
                            <td>{{files.surname}}</td>
                            <td>{{files.age}}</td>
                            <td>{{files.course}}</td>
                            <td>{{files.position}}</td>
                            <td>{{files.partylist}}</td>
                            <td><button class="delete"><a href="{% url 'votingApp:delete' files.id %}">Delete</a></button></td>


                        </tr>
                        {% endfor %}

                    </tbody>
                </table>
            </div>
        </div>
    </form>

   {% comment %}<div class="btns">
        <button id="b">REMOVE</button>
        <button id="b">UPLOAD</button>
    </div>{% endcomment %}

    <div class="last">
        <a type="button" href="{% url 'votingsysApp:index' %}" id="button">LOG OUT</a>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js" integrity="sha384-VHvPCCyXqtD5DqJeNxl2dtTyhF78xXNXdkwX1CZeRusQfRKp+tA7hAShOK/B/fQ2" crossorigin="anonymous"></script>


</body>

</html>

votingsys/votingsysApp/templates/votingsysApp/comelec_login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>TUPC USG</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
    <link rel="stylesheet" href="{%static 'css/index.css'%}">


</head>

<body>
    <div class="kaliwa">
        <img src="{%static 'images/usg.png' %}" alt="usg">
        <a type="text" id="link" href="https://m.facebook.com/775534235865942"><img src="{%static 'images/fblogo.png'%}" alt="logo">TUPC-USG FACEBOOK PAGE</a>
    </div>
    <form action="/comlog/" method="post">
        {% csrf_token %}
        <div class="rect1">

        </div>

        <div class="kanan">
            <div class="inner">
                <h1>COMELEC</h1>
                <h1>LOG IN</h1>
                <div class="inputdiv">
                    <img src="{%static 'images/head.png' %}" alt="head">
                    <input type="email" name="email" id="email" placeholder="abc.def@gsfe.tupcavite.edu.ph">
                </div>
                <div class="inputdiv">
                    <img src="{%static 'images/eye.png' %}" alt="aa">
                    <input type="password" name="pass" id="pass" placeholder="password">
                </div>
                <div class="btn">
                    <button id="b" type="submit" class="tbtn">LOG IN</button>
                    <a id="link" href="{% url 'votingsysApp:regcomelec' %}">SIGN UP</a>
                    <a id="link" href="{% url 'votingApp:index' %}">STUDENT LOG IN</a>
                </div>
            </div>
        </div>

        <div class="rect2">

        </div>
    </form>
    
    <script>
        document.querySelector('.tbtn').onclick = function() {

            var password = document.querySelector('.email').value,
                password2 = document.querySelector('.pass').value;

            if (password == "") {
                alert("Field cannot be empty");
            } 
            return true
        }
    </script>


    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js" integrity="sha384-VHvPCCyXqtD5DqJeNxl2dtTyhF78xXNXdkwX1CZeRusQfRKp+tA7hAShOK/B/fQ2" crossorigin="anonymous"></script>


</body>

</html>

votingsys/votingsysApp/templates/votingsysApp/comelec_reg.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>VOTERS REGISTRATION</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
    <link rel="stylesheet" href="{%static 'css/newuser.css' %}">

</head>

<body>
    <div class="kaliwa1">
        <img src="{%static 'images/usg.png' %}" alt="aa">
    </div>

    <form action="/new/" method="post">
        {% csrf_token %}
        <div class="right">
            <h1>COMELEC REGISTRATION</h1>

            <div class="form-group">
                <input type="text" class="form-control" name="name" id="name" aria-describedby="emailHelp" placeholder="Firstname Lastname" required>

            </div>

            <div class="form-group">
                <input type="email" class="form-control" name="email" id="email" aria-describedby="emailHelp" placeholder="mamamia.miamore@gsfe.tupcavite.edu.ph" required>

            </div>

            <div class="form-group">
                <input type="text" class="form-control" name="idno" id="idno" aria-describedby="emailHelp" placeholder="TUPC-XX-XXXX" required>

            </div>

            <div class="form-group">
                <input type="password" class="password form-control" name="password" id="password" aria-describedby="emailHelp" placeholder="Password" required>

            </div>

            <div class="form-group">
                <input type="password" class="password1 form-control" name="confirm_password" id="confirm_password" aria-describedby="emailHelp" placeholder="Confirm Password" required>

            </div>



            <button type="submit" id="pindot" class="thbtn">Sign Up</button>
            <a type="button" id="aaa" href="{% url 'votingsysApp:index' %}">Student Log In</a>
            <p>Already had an account?<a href="{% url 'votingsysApp:comeleclog' %}">Sign In</a></p>

        </div>

    </form>

    <script>
        document.querySelector('.tbtn').onclick = function() {

            var password = document.querySelector('.password').value,
                password2 = document.querySelector('.password1').value;

            if (password == "") {
                alert("Field cannot be empty");
            } else if (password != password2) {
                alert("Password didn't match try again.");
                document.querySelector('.password').value = '';
                document.querySelector('.password1').value = '';

                return false
            }
            return true
        }
    </script>

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js" integrity="sha384-VHvPCCyXqtD5DqJeNxl2dtTyhF78xXNXdkwX1CZeRusQfRKp+tA7hAShOK/B/fQ2" crossorigin="anonymous"></script>


</body>

</html>

votingsys/votingsysApp/templates/votingsysApp/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>TUPC USG</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
    <link rel="stylesheet" href="{%static 'css/index.css'%}">


</head>

<body>
    <div class="kaliwa">
        <img src="{%static 'images/usg.png' %}" alt="usg">
        <a type="text" id="link" href="https://m.facebook.com/775534235865942"><img src="{%static 'images/fblogo.png'%}" alt="logo">TUPC-USG FACEBOOK PAGE</a>
    </div>
    <form action="{% url 'votingsysApp:userlogin' %}" method="post">
        {% csrf_token %}
        <div class="rect1">

        </div>

        <div class="kanan">
            <div class="inner">
                <h1>WELCOME</h1>
                <h1>TUPcian!</h1>
                <div class="inputdiv">
                    <img src="{%static 'images/head.png' %}" alt="head">
                    <input type="email" name="email" id="email" placeholder="abc.def@gsfe.tupcavite.edu.ph">
                </div>
                <div class="inputdiv">
                    <img src="{%static 'images/eye.png' %}" alt="aa">
                    <input type="password" name="pass" id="pass" placeholder="password">
                </div>
                <div class="btn">
                    <a id="b" href="homepage.html">LOG IN</a>
                    <a id="link" href="{% url 'votingsysApp:newreg1' %}">SIGN UP</a>
                    <a href="{% url 'votingsysApp:comeleclog' %}">COMELEC LOG IN</a>
                </div>
            </div>
        </div>

        <div class="rect2">

        </div>
    </form>
    <script>
        document.querySelector('.tbtn').onclick = function() {

            var password = document.querySelector('.email').value,
                password2 = document.querySelector('.pass').value;

            if (password == "") {
                alert("Field cannot be empty");
            } 
            return true
        }
    </script>


    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js" integrity="sha384-VHvPCCyXqtD5DqJeNxl2dtTyhF78xXNXdkwX1CZeRusQfRKp+tA7hAShOK/B/fQ2" crossorigin="anonymous"></script>


</body>

</html>

votingsys/votingsysApp/templates/votingsysApp/newreg.html
<!DOCTYPE html>
{%load static%}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>VOTERS REGISTRATION</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
    <link rel="stylesheet" href="{%static 'css/newuser.css' %}">

</head>

<body>
    <div class="kaliwa1">
        <img src="{%static 'images/usg.png' %}" alt="aa">
    </div>

    <form action="/new/" method="post">
        {% csrf_token %}
        <div class="right">
            <h1>REGISTRATION</h1>

            <div class="form-group">
                <input type="text" class="form-control" name="name" id="name" aria-describedby="emailHelp" placeholder="Firstname Lastname" required>

            </div>

            <div class="form-group">
                <input type="email" class="form-control" name="email" id="email" aria-describedby="emailHelp" placeholder="mamamia.miamore@gsfe.tupcavite.edu.ph" required>

            </div>

            <div class="form-group">
                <input type="text" class="form-control" name="idno" id="idno" aria-describedby="emailHelp" placeholder="TUPC-XX-XXXX" required>

            </div>

            <div class="form-group">
                <input type="password" class="password form-control" name="password" id="password" aria-describedby="emailHelp" placeholder="Password" required>

            </div>

            <div class="form-group">
                <input type="password" class="password1 form-control" name="confirm_password" id="confirm_password" aria-describedby="emailHelp" placeholder="Confirm Password" required>

            </div>



            <button type="submit" id="pindot" class="tbtn">Sign Up</button>
            <p>Already had an account?<a href="{% url 'votingsysApp:index' %}">Log In</a></p>

        </div>

    </form>

    <script>
        document.querySelector('.tbtn').onclick = function() {

            var password = document.querySelector('.password').value,
                password2 = document.querySelector('.password1').value;

            if (password == "") {
                alert("Field cannot be empty");
            } else if (password != password2) {
                alert("Password didn't match try again.");
                document.querySelector('.password').value = '';
                document.querySelector('.password1').value = '';

                return false
            }
            return true
        }
    </script>

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js" integrity="sha384-VHvPCCyXqtD5DqJeNxl2dtTyhF78xXNXdkwX1CZeRusQfRKp+tA7hAShOK/B/fQ2" crossorigin="anonymous"></script>


</body>

</html>